In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [17]:
df=pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
#see basic information about dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [12]:
#to see null values in dataset
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [13]:
#to see duplicate value 
df.duplicated().sum()

0

In [22]:
#perform One-Hot-Encoding for change categorical to numerical 
ohe=OneHotEncoder(sparse=False,drop='first',dtype=np.int32)
col=['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope']
encode_data=ohe.fit_transform(df[col])

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [29]:
names=ohe.get_feature_names_out()
d=pd.DataFrame(encode_data,columns=names)
df=pd.concat([df,d],axis=1)
df.drop(col,axis=1,inplace=True)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,...,ST_Slope_Up,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,...,1,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,...,1,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,...,0,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,...,1,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,1,0,0,...,0,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,1,0,0,...,0,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,1,0,0,...,0,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,1,0,1,0,...,0,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,1,...,1,1,0,1,0,1,0,0,0,1

In [31]:
x=df.drop('HeartDisease',axis=1)
y=df['HeartDisease']

In [32]:
#split data in train and test data

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [34]:
#perform Standardisation 
std=StandardScaler()
std.fit(x_train)
new_xtrain=std.transform(x_train)
new_xtest=std.transform(x_test)

In [38]:
x_train=pd.DataFrame(new_xtrain,columns=x_train.columns)
x_test=pd.DataFrame(new_xtest,columns=x_test.columns)

In [41]:
x_train.describe().round(2)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,...,ST_Slope_Up,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
count,734.00,734.00,734.00,734.00,734.00,734.00,734.00,734.00,734.00,734.00,...,734.00,734.00,734.00,734.00,734.00,734.00,734.00,734.00,734.0,734.00
mean,-0.00,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,...,-0.00,0.00,0.00,0.00,-0.00,0.00,0.00,-0.00,0.0,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.0,1.00
min,-2.74,-2.27,-1.89,-0.54,-2.97,-3.28,-1.92,-0.49,-0.54,-0.22,...,-0.89,-1.92,-0.49,-0.54,-0.22,-1.22,-0.49,-0.81,-1.0,-0.89
25%,-0.69,-0.71,-0.21,-0.54,-0.65,-0.82,0.52,-0.49,-0.54,-0.22,...,-0.89,0.52,-0.49,-0.54,-0.22,-1.22,-0.49,-0.81,-1.0,-0.89
50%,0.07,-0.16,0.23,-0.54,0.04,-0.35,0.52,-0.49,-0.54,-0.22,...,-0.89,0.52,-0.49,-0.54,-0.22,0.82,-0.49,-0.81,-1.0,-0.89
75%,0.71,0.40,0.62,-0.54,0.78,0.59,0.52,-0.49,-0.54,-0.22,...,1.13,0.52,-0.49,-0.54,-0.22,0.82,-0.49,1.24,1.0,1.13
max,2.54,3.74,3.47,1.84,2.52,5.04,0.52,2.06,1.84,4.61,...,1.13,0.52,2.06,1.84,4.61,0.82,2.03,1.24,1.0,1.13

In [42]:
#Train the model
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print('Accuracy score of model= ', accuracy)

Accuracy score of model=  0.7934782608695652